### ISSUE TITLE
strict-imports toggle doesn't seem to work when run by pre-commit

### ISSUE THREAD

**Issue by Goldziher** [ariebovenberg/slotscheck#113]
Hi, 

I tried configuring `no-strict-imports` i pyproject.toml, but running the tool via pre-commit ignored this completely. I concluded it probably doesn't read the pyproject.toml file inside pre-commit, so I insterad tried doing this in my pre-commit config:

```yaml
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.14.1
    hooks:
      - id: slotscheck
        exclude: "test_*"
        args: [--no-strict-imports]
```

But the tool keeps complaining about imports. I think it simply doesn't pick the config.
