### ISSUE TITLE
pre-commit example does not work on windows

### ISSUE THREAD

**Issue by spacemanspiff2007** [ariebovenberg/slotscheck#269]
The pre-commit from the [docs](https://slotscheck.readthedocs.io/en/latest/advanced.html#pre-commit-hook) does not work on windows:
````yaml
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
    - id: slotscheck
      entry: env PYTHONPATH=src slotscheck --verbose
````
output:
````
slotscheck...............................................................Failed
- hook id: slotscheck
- exit code: 1

Executable `env` not found
````

Edit:
I think it's easier to run slotscheck with tox than with pre-commit. With tox normally all required dependencies are installed anyways and it's easy to change the working directory:

````
[testenv:slotscheck]
deps =
    -r{toxinidir}/requirements.txt
    slotscheck
change_dir = {toxinidir}/src
commands =
    python -m slotscheck <NAME_OF_MODULE> --verbose
````
